"""PDF generation service for lawyer handoff packages."""

from datetime import datetime
from io import BytesIO
from pathlib import Path
from zipfile import ZipFile

from jinja2 import Environment, FileSystemLoader
from weasyprint import HTML, CSS

from models.criteria import ChallengeSession, O1Assessment
from models.resume import ParsedResume


def generate_assessment_pdf(
    assessment: O1Assessment,
    parsed_resume: ParsedResume,
    challenges: dict[str, ChallengeSession],
    score: int,
    tier: str,
) -> bytes:
    """Generate a PDF report from assessment data.

    Args:
        assessment: The O1Assessment with all criteria evaluations
        parsed_resume: The parsed resume data
        challenges: Dictionary of criterion name to ChallengeSession
        score: Number of criteria met (0-8)
        tier: Case strength tier ("Strong", "Moderate", "Needs Work")

    Returns:
        PDF file as bytes
    """
    template_dir = Path(__file__).parent.parent / "templates" / "pdf"
    env = Environment(loader=FileSystemLoader(template_dir))
    template = env.get_template("assessment_report.html")

    html_content = template.render(
        assessment=assessment,
        parsed_resume=parsed_resume,
        challenges=challenges,
        score=score,
        tier=tier,
        generated_at=datetime.now().strftime("%B %d, %Y at %I:%M %p"),
    )

    css_path = template_dir / "pdf_styles.css"
    pdf_bytes = HTML(string=html_content, base_url=str(template_dir)).write_pdf(
        stylesheets=[CSS(filename=str(css_path))]
    )

    return pdf_bytes


def create_lawyer_handoff_zip(
    assessment: O1Assessment,
    parsed_resume: ParsedResume,
    challenges: dict[str, ChallengeSession],
    score: int,
    tier: str,
    original_file_bytes: bytes,
    original_filename: str,
) -> bytes:
    """Create a ZIP file containing the assessment PDF and original resume.

    Args:
        assessment: The O1Assessment with all criteria evaluations
        parsed_resume: The parsed resume data
        challenges: Dictionary of criterion name to ChallengeSession
        score: Number of criteria met (0-8)
        tier: Case strength tier
        original_file_bytes: The original uploaded file as bytes
        original_filename: Original filename of the uploaded resume

    Returns:
        ZIP file as bytes
    """
    pdf_bytes = generate_assessment_pdf(
        assessment=assessment,
        parsed_resume=parsed_resume,
        challenges=challenges,
        score=score,
        tier=tier,
    )

    zip_buffer = BytesIO()
    with ZipFile(zip_buffer, "w") as zip_file:
        zip_file.writestr("o1a_assessment_report.pdf", pdf_bytes)
        zip_file.writestr(f"original_{original_filename}", original_file_bytes)
        readme_content = _generate_readme(original_filename)
        zip_file.writestr("README.txt", readme_content)

    zip_buffer.seek(0)
    return zip_buffer.read()


def _generate_readme(original_filename: str) -> str:
    """Generate README explaining the package contents."""
    return f"""O-1A Visa Assessment Package
Generated: {datetime.now().strftime("%B %d, %Y")}

Contents:
---------
1. o1a_assessment_report.pdf - AI-generated assessment of O-1A visa criteria
2. original_{original_filename} - Original resume as uploaded

Notes for Attorney:
-------------------
- The assessment report analyzes the resume against all 8 O-1A evidentiary criteria
- Each criterion includes evidence found, reasoning, and any challenge conversation transcripts
- The AI assessment is a starting point - human legal review is essential
- Challenge conversations may contain additional evidence disclosed by the applicant

This package was generated by Alien (O-1A Visa Readiness Analyzer).
"""
